package com.douban.movie.spider.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.douban.movie.spider.entity.Movie;

@Mapper
public interface MovieMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table movie
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table movie
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	int insert(Movie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table movie
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	int insertSelective(Movie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table movie
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	Movie selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table movie
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	int updateByPrimaryKeySelective(Movie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table movie
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	int updateByPrimaryKey(Movie record);

	/**
	 * 根据urlMd5获取movie信息
	 * 
	 * @param urlMd5
	 *            加密的url
	 * @return movie对象
	 */
	Movie queryByUrlMd5(@Param("urlMd5") String urlMd5);

	List<Movie> queryMoviesByPage(@Param("startIndex") int page, @Param("pageNum") int pageNum);

	int insertExceptId(Movie record);
}