package com.douban.movie.spider.mapper;

import org.apache.ibatis.annotations.Param;

import com.douban.movie.spider.entity.Music;

public interface MusicMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table music
	 *
	 * @mbg.generated Mon Aug 28 19:43:31 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table music
	 *
	 * @mbg.generated Mon Aug 28 19:43:31 CST 2017
	 */
	int insert(Music record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table music
	 *
	 * @mbg.generated Mon Aug 28 19:43:31 CST 2017
	 */
	int insertSelective(Music record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table music
	 *
	 * @mbg.generated Mon Aug 28 19:43:31 CST 2017
	 */
	Music selectByPrimaryKey(Integer id);

	Music queryByUrlMd5(@Param("urlMd5") String urlMd5);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table music
	 *
	 * @mbg.generated Mon Aug 28 19:43:31 CST 2017
	 */
	int updateByPrimaryKeySelective(Music record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table music
	 *
	 * @mbg.generated Mon Aug 28 19:43:31 CST 2017
	 */
	int updateByPrimaryKey(Music record);
}