package com.douban.movie.spider.entity;

public class Movie {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column movie.id
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column movie.name
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column movie.score
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	private Float score;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column movie.url
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	private String url;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column movie.url_md5
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	private String urlMd5;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column movie.pic
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	private String pic;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column movie.bk_field1
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	private String bkField1;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column movie.bk_field2
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	private String bkField2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column movie.bk_field3
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	private String bkField3;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column movie.id
	 *
	 * @return the value of movie.id
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column movie.id
	 *
	 * @param id
	 *            the value for movie.id
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column movie.name
	 *
	 * @return the value of movie.name
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column movie.name
	 *
	 * @param name
	 *            the value for movie.name
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column movie.score
	 *
	 * @return the value of movie.score
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public Float getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column movie.score
	 *
	 * @param score
	 *            the value for movie.score
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public void setScore(Float score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column movie.url
	 *
	 * @return the value of movie.url
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column movie.url
	 *
	 * @param url
	 *            the value for movie.url
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column movie.url_md5
	 *
	 * @return the value of movie.url_md5
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public String getUrlMd5() {
		return urlMd5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column movie.url_md5
	 *
	 * @param urlMd5
	 *            the value for movie.url_md5
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public void setUrlMd5(String urlMd5) {
		this.urlMd5 = urlMd5 == null ? null : urlMd5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column movie.pic
	 *
	 * @return the value of movie.pic
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column movie.pic
	 *
	 * @param pic
	 *            the value for movie.pic
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public void setPic(String pic) {
		this.pic = pic == null ? null : pic.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column movie.bk_field1
	 *
	 * @return the value of movie.bk_field1
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public String getBkField1() {
		return bkField1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column movie.bk_field1
	 *
	 * @param bkField1
	 *            the value for movie.bk_field1
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public void setBkField1(String bkField1) {
		this.bkField1 = bkField1 == null ? null : bkField1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column movie.bk_field2
	 *
	 * @return the value of movie.bk_field2
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public String getBkField2() {
		return bkField2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column movie.bk_field2
	 *
	 * @param bkField2
	 *            the value for movie.bk_field2
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public void setBkField2(String bkField2) {
		this.bkField2 = bkField2 == null ? null : bkField2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column movie.bk_field3
	 *
	 * @return the value of movie.bk_field3
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public String getBkField3() {
		return bkField3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column movie.bk_field3
	 *
	 * @param bkField3
	 *            the value for movie.bk_field3
	 *
	 * @mbg.generated Wed Aug 16 19:57:55 CST 2017
	 */
	public void setBkField3(String bkField3) {
		this.bkField3 = bkField3 == null ? null : bkField3.trim();
	}

	@Override
	public String toString() {
		return "Movie [id=" + id + ", name=" + name + ", score=" + score + ", url=" + url + ", urlMd5=" + urlMd5
				+ ", pic=" + pic + ", bkField1=" + bkField1 + ", bkField2=" + bkField2 + ", bkField3=" + bkField3 + "]";
	}
}