package com.douban.movie.spider.entity;

public class Music {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.id
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.name
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.url
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.url_md5
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    private String urlMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.singer
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    private String singer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.comment
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    private Integer comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.score
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    private Float score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.publish_time
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    private String publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.category
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.tag
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.bk_field1
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    private String bkField1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.bk_field2
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    private String bkField2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.bk_field3
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    private String bkField3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.img
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.id
     *
     * @return the value of music.id
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.id
     *
     * @param id the value for music.id
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.name
     *
     * @return the value of music.name
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.name
     *
     * @param name the value for music.name
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.url
     *
     * @return the value of music.url
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.url
     *
     * @param url the value for music.url
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.url_md5
     *
     * @return the value of music.url_md5
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public String getUrlMd5() {
        return urlMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.url_md5
     *
     * @param urlMd5 the value for music.url_md5
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public void setUrlMd5(String urlMd5) {
        this.urlMd5 = urlMd5 == null ? null : urlMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.singer
     *
     * @return the value of music.singer
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public String getSinger() {
        return singer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.singer
     *
     * @param singer the value for music.singer
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public void setSinger(String singer) {
        this.singer = singer == null ? null : singer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.comment
     *
     * @return the value of music.comment
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public Integer getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.comment
     *
     * @param comment the value for music.comment
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public void setComment(Integer comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.score
     *
     * @return the value of music.score
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.score
     *
     * @param score the value for music.score
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.publish_time
     *
     * @return the value of music.publish_time
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.publish_time
     *
     * @param publishTime the value for music.publish_time
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime == null ? null : publishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.category
     *
     * @return the value of music.category
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.category
     *
     * @param category the value for music.category
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.tag
     *
     * @return the value of music.tag
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.tag
     *
     * @param tag the value for music.tag
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.bk_field1
     *
     * @return the value of music.bk_field1
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public String getBkField1() {
        return bkField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.bk_field1
     *
     * @param bkField1 the value for music.bk_field1
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public void setBkField1(String bkField1) {
        this.bkField1 = bkField1 == null ? null : bkField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.bk_field2
     *
     * @return the value of music.bk_field2
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public String getBkField2() {
        return bkField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.bk_field2
     *
     * @param bkField2 the value for music.bk_field2
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public void setBkField2(String bkField2) {
        this.bkField2 = bkField2 == null ? null : bkField2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.bk_field3
     *
     * @return the value of music.bk_field3
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public String getBkField3() {
        return bkField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.bk_field3
     *
     * @param bkField3 the value for music.bk_field3
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public void setBkField3(String bkField3) {
        this.bkField3 = bkField3 == null ? null : bkField3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.img
     *
     * @return the value of music.img
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.img
     *
     * @param img the value for music.img
     *
     * @mbg.generated Mon Aug 28 19:43:31 CST 2017
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}